# Generated by Django 4.1.7 on 2023-04-01 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Estanterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Estanteria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('numero_Paginas', models.CharField(max_length=200)),
                ('id_Clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApi.clientes')),
                ('id_Estanterias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApi.estanterias')),
                ('id_Tipo_libros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApi.tipolibros')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApi.genero'),
        ),
    ]
